const return404 = () => new Response('Page Not found', { status: 404 })
export const GET = async () => return404()
export const HEAD = async () => return404()
export const POST = async () => return404()
export const PUT = async () => return404()
export const DELETE = async () => return404()
export const PATCH = async () => return404()
export const OPTIONS = async () => return404()